### ISSUE TITLE
Ramdom.py : ugly outputs

### ISSUE THREAD

**Issue by Shurtugal** [Dashcom/dashcom_bot#3]
Random.py output text with comas between words : try using + between words.

**Comment by Dashcom** [comment]
The console return :
TypeError: cannot concatenate 'str' and 'int' objects

**Comment by Dashcom** [comment]
Resolved ! (thx internet)
it possible to use print('srt str {} str str {}'.format(var1, var2)
it returns (considering var 1 = 1, var2 = 2) str str 1 str str 2

**Comment by Shurtugal** [comment]
Yes, you can transform int in str like this : str(int)
Exemple : print('mot de '+str(len(wd))+' lettres, commencant par '+str(wd[0]))
