### ISSUE TITLE
Ugly an non-ergonomic input methods

### ISSUE THREAD

**Issue by Dashcom** [Dashcom/dashcom_bot#6]
The input() fonction need 'srt' to import some text, you should use raw_input().
This change also may need to change 
R=input()
    if R=='':
on line 33

**Comment by Shurtugal** [comment]
Or I could simply transform input() in str(input()).
Yes, I only want to use input().

**Comment by Shurtugal** [comment]
Edit : it only works if input() returns a number. So I will have one raw_input() and one str(input()) in Reso.py.
